paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos disponibles
      tags:
        - Productos
      responses:
        '200':
          description: La operación fue exitosa.
        '400':
          description: Se envió un dato no esperado.
        '500':
          description: Error inesperado en el servidor.
    post:
      summary: Crea un nuevo producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/products'
      responses:
        '201':
          description: Producto creado correctamente
        '400':
          description: Error al crear el producto
        '500':
          description: Error en el servidor

  /api/products/{pid}:
    get:
      summary: Obtiene un producto a partir de su ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se desea solicitar
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/products'
        '400':
          description: Producto no encontrado.
        '500':
          description: Error inesperado en el servidor.
    put:
      summary: Actualiza un producto
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se desea actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/products'
      responses:
        '200':
          description: Producto actualizado correctamente
        '400':
          description: Error al actualizar el producto
        '500':
          description: Error en el servidor
    delete:
      summary: Borra un producto
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se desea eliminar
          schema:
            type: string
      responses:
        '200':
          description: Producto borrado correctamente
        '400':
          description: Error al borrar el producto
        '500':
          description: Error en el servidor

components:
  schemas:
    products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por MongoDB
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: Imagen del producto
        code:
          type: number
          description: Código del producto
        stock:
          type: number
          description: Stock disponible del producto
